name: web
region: nyc3
services:
  - name: web
    git:
      branch: master
      repo_clone_url: https://github.com/vadikmarmeladov/lot-systems.git
    build_command: |
      echo "🚀 Build started at $(date)"
      
      # Install dependencies
      echo "📦 Installing dependencies..."
      yarn install --frozen-lockfile --production=false
      
      # Build everything (client + server)
      echo "🛠 Building application..."
      NODE_ENV=production yarn build
      
      # Verify build output
      echo "📁 Verifying build output..."
      echo "Client JS files:"
      ls -la dist/client/js/ | head -20
      echo "Client CSS files:"
      ls -la dist/client/css/
      echo "Server files:"
      ls -la dist/server/server/ | head -10
      echo "Templates:"
      ls -la templates/
      echo "Public files:"
      ls -la public/ | head -10
      
      if [ ! -f "dist/client/js/login.js" ]; then
        echo "❌ Client JS build output missing!"
        exit 1
      fi
      
      if [ ! -f "dist/server/server/index.js" ]; then
        echo "❌ Server build output missing!"
        exit 1
      fi

      echo "✅ Build completed successfully at $(date)"
    run_command: node dist/server/server/index.js
    environment_slug: node-js
    instance_size_slug: basic-xxs
    instance_count: 1
    http_port: 8080
    health_check:
      http_path: /health
      initial_delay_seconds: 30
    envs:
      - key: NODE_ENV
        scope: RUN_AND_BUILD_TIME
        value: production
      - key: DATABASE_URL
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: "postgresql://doadmin:AVNS_8V6Hqzuxwj0JkMxgNvR@db-postgresql-nyc3-92053-do-user-22640384-0.f.db.ondigitalocean.com:25060/defaultdb?sslmode=require"
      - key: PORT
        scope: RUN_TIME
        value: "8080"
      - key: APP_NAME
        scope: RUN_TIME
        value: "LOT Systems"
      - key: APP_HOST
        scope: RUN_TIME
        value: "${_self.PUBLIC_URL}"
      - key: JWT_SECRET
        scope: RUN_AND_BUILD_TIME
        type: SECRET
        value: "13919320b2a8816ced947b7a6385811b"
      - key: RESEND_API_KEY
        scope: RUN_TIME
        type: SECRET
        value: "re_83s23f6W_LbDfdmmXpXJ4je4i2kt1HA7u"
      - key: RESEND_FROM_EMAIL
        scope: RUN_TIME
        value: "support@lot-systems.com"
      - key: RESEND_FROM_NAME
        scope: RUN_TIME
        value: "LOT Systems"
